'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@k2w/ui/card';
import { Alert, AlertDescription } from '@k2w/ui/alert';
import { Progress } from '@k2w/ui/progress';
import { Search, FileText, CheckCircle, AlertCircle } from 'lucide-react';
import { toast } from 'sonner';

// Import React Query hooks
import { useSubmitKeyword, useKeywordHistory } from '../hooks/use-api';

// Import components
import { PageHeader, KeywordSubmissionForm, KeywordList } from '../components';

interface KeywordFormData {
  keyword: string;
  region: string;
  language: string;
}

export default function HomePage() {
  // React Query hooks
  const { data: keywordHistoryData, refetch: refetchHistory } = useKeywordHistory({
    page: 1,
    limit: 10,
  });
  const submitKeywordMutation = useSubmitKeyword();

  // Get keywords from API data
  const submittedKeywords = keywordHistoryData?.data?.keywords || [];
  const quotaUsed = submittedKeywords.length;
  const quotaLimit = 100;

  const handleSubmit = (formData: KeywordFormData) => {
    if (quotaUsed >= quotaLimit) {
      toast.error('You have reached your monthly keyword limit');
      return;
    }

    // Submit using React Query mutation
    submitKeywordMutation.mutate(formData, {
      onSuccess: () => {
        // Refetch history to show new keyword
        refetchHistory();
      },
    });
  };

  const handleViewContent = () => {
    // Navigate to content details page
    window.open('/dashboard', '_blank');
  };

  const quotaPercentage = (quotaUsed / quotaLimit) * 100;

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <PageHeader 
          title="K2W Content Generator"
          description="Transform keywords into high-quality, SEO-optimized content with AI"
        />
          
        {/* Quota Display */}
        <Card className="max-w-md mx-auto mb-8">
          <CardHeader className="pb-3">
            <CardTitle className="text-lg">Monthly Usage</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span>Keywords used</span>
                <span>{quotaUsed} / {quotaLimit}</span>
              </div>
              <Progress value={quotaPercentage} className="h-2" />
              {quotaPercentage > 80 && (
                <Alert>
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>
                    You&apos;re approaching your monthly limit
                  </AlertDescription>
                </Alert>
              )}
            </div>
          </CardContent>
        </Card>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Keyword Submission Form */}
          <KeywordSubmissionForm 
            onSubmit={handleSubmit}
            isSubmitting={submitKeywordMutation.isPending}
            disabled={quotaUsed >= quotaLimit}
          />

          {/* Recent Submissions */}
          <Card>
            <CardHeader>
              <CardTitle>Recent Submissions</CardTitle>
              <CardDescription>
                Track the progress of your content generation
              </CardDescription>
            </CardHeader>
            <CardContent>
              <KeywordList 
                keywords={submittedKeywords}
                isLoading={false}
                onViewContent={handleViewContent}
              />
            </CardContent>
          </Card>
        </div>

        {/* Features Section */}
        <div className="mt-16 text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-8">
            Powered by Advanced AI
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="bg-blue-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <Search className="h-8 w-8 text-blue-600" />
              </div>
              <h3 className="text-xl font-semibold mb-2">SEO Research</h3>
              <p className="text-gray-600">
                Deep competitor analysis and keyword research using AlsoAsked and SurferSEO
              </p>
            </div>
            
            <div className="text-center">
              <div className="bg-purple-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <FileText className="h-8 w-8 text-purple-600" />
              </div>
              <h3 className="text-xl font-semibold mb-2">AI Content</h3>
              <p className="text-gray-600">
                High-quality, engaging content generated by GPT-4 with perfect SEO optimization
              </p>
            </div>
            
            <div className="text-center">
              <div className="bg-green-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <CheckCircle className="h-8 w-8 text-green-600" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Quality Assurance</h3>
              <p className="text-gray-600">
                Grammar checking with Grammarly and plagiarism detection with Copyscape
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
